"""Audit system constants and configuration values.

This module defines constants used across the audit system for tracking
entity creation, updates, and archiving (deletion).
"""

# Fields to exclude when creating entities from data
# These fields are either auto-generated by entities or set explicitly in repositories
AUDIT_FIELDS_EXCLUDE = {
    "id",  # Auto-generated by Identity entity (ULID)
    "created_at",  # Auto-generated by Timestamp entity
    "updated_at",  # Auto-generated by Timestamp entity
    "created_by",  # Set explicitly in repository create/update methods
    "updated_by",  # Set explicitly in repository create/update methods
}
