"""create restaurant_owners table.

Revision ID: 477b681fcc75
Revises: 5f5134a918f7
Create Date: 2025-10-23 09:37:35.594840

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "477b681fcc75"
down_revision: str | None = "5f5134a918f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurant_owners",
        sa.Column(
            "created_by", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True
        ),
        sa.Column(
            "updated_by", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "restaurant_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False
        ),
        sa.Column(
            "owner_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False
        ),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
        ),
        sa.PrimaryKeyConstraint("restaurant_id", "owner_id"),
    )
    # Note: SQLite doesn't support ALTER COLUMN for server_default changes
    # These changes are cosmetic and don't affect functionality
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("restaurant_owners")
    # Note: SQLite doesn't support ALTER COLUMN for server_default changes
    # ### end Alembic commands ###
